# Generated by Django 5.0.2 on 2024-02-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbies',
            name='image',
            field=models.CharField(default='default.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.CharField(default='default.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
