# Generated by Django 5.0.2 on 2024-02-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0002_hobbies_image_portfolio_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=400)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='image',
            field=models.CharField(default='https://res.cloudinary.com/dqnqbaqf9/image/upload/v1633020018/about-mckp1_df1wt4.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.CharField(default='https://res.cloudinary.com/dqnqbaqf9/image/upload/v1633020018/about-mckp1_df1wt4.jpg', max_length=500),
        ),
    ]
